---

- name: Add multiple users to worker nodes
  hosts: webservers
  become: yes
  vars:
    users:
    - Rana
    - Bilal
    - Nida
    - Hassan
    - Everyoneelse
  tasks: 
   - name: Add a list of users
     user:
       name:  "{{ item }}"
       state: present
     with_items: "{{ users }}"   
